import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * The Controller class is responsible for handling user interactions
 * with a calculator interface, responding to button clicks and triggering
 * appropriate actions in the associated Model.
 *
 * This class implements the addActionListener interface to capture
 * ActionEvents generated by buttons in the calculator interface.
 *
 */

public class Controller implements ActionListener{
    private Model model;

    /**
     * Constructs a new Controller instance.
     *
     * @param viewer The viewer component of the calculator interface.
     */

    Controller(Viewer viewer){
        model = new Model(viewer);
    }

    /**
    * Handles user interactions by responding to ActionEvents generated
    * by buttons in the calculator interface.
    *
    * @param event  ActionEvent object that gives information about the event and its source.
    */
    @Override
    public void actionPerformed(ActionEvent event){
        // Extract the actionCommand associated with the button (typically a String)
        String command = event.getActionCommand();
        // Delegate the action to the associated Model
        model.doAction(command);


    }

}
